<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, user-scalable=no"
    />
    <title>XHR - Load JSON</title>
    <style>
      body {
        font-family: sans-serif;
      }
    </style>
  </head>
  <body>
    <h2>XHR - Load JSON</h2>

    <hr />
    <button id="my-button">Load Data</button>
    <div id="output">Click button to load</div>

    <script>
      document.querySelector("#my-button").onclick = loadJsonFetch;

      // A - simple version, no error handling
      /*
      async function loadJsonFetch() {
        // await ( "stay on this line") until the first promise is resolved
        let response = await fetch("https://swapi.dev/api/people/1");

        //await ( "stay on this line") until the second promise is resolved
        let json = await response.json();
        console.log(json); // name: 'Luke Skywalker', height: '172', etc
        console.log(json.name); //Luke Skywalker
        console.log(json.homeworld);
      }
      */

      // B - Handles errors with try/catch
      /*
      async function loadJsonFetch() {
        try {
          // await ( "stay on this line") until the first promise is resolved
          let response = await fetch("https://swapi.dev/api/people/1");

          if (!response.ok) {
            if (response.status == 404) console.log("Do 404 stuff!");
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          //await ( "stay on this line") until the second promise is resolved
          let json = await response.json();
          console.log(json); // name: 'Luke Skywalker', height: '172', etc
          console.log(json.name); //Luke Skywalker
          console.log(json.homeworld);
        } catch (e) {
          console.log(`In catch with e = ${e}`);
        }
      }
      */

      // C - Uses .catch() for error handling
      function loadJsonFetch() {
        const fetchPromise = async () => {
          // await ( "stay on this line") until the first promise is resolved
          // let response = await fetch("https://swapi.dev/api/people/1");
          let response = await fetch("data/pet-names.json");
          // if the response is not successfull, throw an error
          if (!response.ok) {
            if (response.status == 404) console.log("Do 404 stuff!");
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          // await ( "stay on this line") until the second promise is resolved
          // Meaning we now have a JSON object
          let json = await response.json();

          const dogNames = json["c9532dc9"]["namelist"];
          const catNames = json["69bab900"]["namelist"];

          const dogHtml = dogNames.map((w) => `<li>${w}</li>`).join("");
          const catHtml = catNames.map((w) => `<li>${w}</li>`).join("");

          document.querySelector("#output").innerHTML = `
          <h3> Dog Names</h3><ol> ${dogHtml} </ol>
          <h3> Cat Names</h3><ol> ${catHtml} </ol>`;
          /*
          console.log(json); // name: 'Luke Skywalker', height: '172', etc
          console.log(json.name); //Luke Skywalker
          console.log(json.homeworld);
          */
        };
        // call fetchPromise() and add a .catch() to it
        // this works because fetchPromise is async and thus returns a promise!
        fetchPromise().catch((e) => {
          console.log(`In catch with e = ${e}`);
        });
      }
    </script>
  </body>
</html>
